name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [aws-runner]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download and Install Maven (manual)  # Less recommended
        run: source ~/.bashrc
      - name: Build Project
        run: mvn clean install -DskipTests
