name: CICD

on:
  push:
    branches: [master]




jobs:
  build:
    runs-on: aws-runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Maven
      run: |
        # Set Maven home and update PATH
        export MAVEN_HOME=/opt/apache-maven-3.9.7
        export PATH=$MAVEN_HOME/bin:$PATH

        # Verify Maven installation
        mvn -version

    - name: Build with Maven
      run: mvn clean install -DskipTests
