name: CICD

on:
  push:
    branches: [master]



jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt-openjdk'

    - name: Configure Maven
      run: |
        # Set Maven home and update PATH
        export MAVEN_HOME=/usr/share/apache-maven-3.8.8
        export PATH=$MAVEN_HOME/bin:$PATH

        # Verify Maven installation
        mvn -version

    - name: Build with Maven
      run: mvn clean install -DskipTests
