name: CICD

on:
  push:
    branches: [master]




jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      


    - name: Verify Maven installation
      run: |
        # Print Maven version to ensure it's available
        mvn -version
        # Print PATH to debug any issues
        echo $PATH

    - name: Build with Maven
      run: mvn clean install -DskipTests
